### PR TITLE
Add tests & fix #3

### LINKED ISSUE #3: Arrays Broken
Hi, Since the merge of #2, the array example no longer works:

```
$ typeset -a Colors=([0]="red" [1]="green" [2]="blue")
$ typeset | grep ^Colors= | ./redi.sh -a
$ ./redi.sh -ag Colors
```
Gives the output:
```
Colors=([0]="redgreenblue")
```
(Tested on Centos 6, Redis 2.8.4)

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by crypt1d** [comment]
Please see my comment in #4  regarding the makefile.

**Comment by fenollp** [comment]
I agree with the comments over #4, however this Makefile only introduces a `test` target.
Would you prefer I replace the Makefile with a third script "run_tests.sh"?

**Comment by crypt1d** [comment]
The main point of the comment was whether we should sacrifice current simplicity of redi.sh in order to introduce a new feature like a Makefile. Same thing applies here, except in this case, in addition to a Makefile we are adding two more scripts. I feel like its an unnecessary burden to redi.sh original goal - a simple redis client.
I'd prefer if we keep the client to a single shell script. However, it seems like this project is gaining some interest, so we could add a small CI job to test its functionality on every pull request. I think I have a Travis account somewhere which we could use for this purpose.

P.S. we should still fix #3 though.

**Comment by fenollp** [comment]
I mean, these test files are completely independent to redi.sh.
Plus, this is already a multi-files project (README.md)...

What's wrong with having a couple test files?
I can write a Travis / Circle CI script & probably embed these files there. Note: that would add a new file (the CI script lives in the project root).
You have to activate either Travis or Circle (or both) yourself though

**Comment by crypt1d** [comment]
Nothing wrong, I'm just considering if its worth it :) Perhaps one script for testing both vars and arrays would be sufficient?

**Comment by fenollp** [comment]
Updated

**Pull request merged**
