### PR TITLE
Create makefile

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by crypt1d** [comment]
Hmm I'm not convinced this is really necessary. So far redi.sh has been a single-file thing, making it pretty easy to manage, installation is as easy as copying it to ur favorite bin/ directory.

Adding a Makefile introduces a slight complexity into the mix, which I'm not sure is justified. Does one really need a make command to replace cp?

**Comment by jarriztg** [comment]
im making a bot in telegram and i need a script to redis but redis-bash-cli actually isnt compatible with arrays and caquino is offline

**Comment by jarriztg** [comment]
can you add something like select the name of the dababatse?
example:
```
echo "hello everybody" | ./redi.sh -d hello
./redi.sh -g hello
```
returns:  `hello everybody`

**Comment by crypt1d** [comment]
@jarriztg yes, I don't see why not. Will do

**Comment by crypt1d** [comment]
@jarriztg now you can do something like:

`echo "this is a variable" | ./redi.sh -s hello
 ./redi.sh -g hello
`

which will return `this is a variable`. 

If you were referring to actual redis databases, those are specified by an index and not by name.

**Comment by jarriztg** [comment]
Thaankss!!! Really i need that because im doing a bot of telegram bash and i need a redis

**Pull request closed without merging**
